
enum Role {
  PACKAGE_VIEW = 'PACKAGE_VIEW',
  PACKAGE_CREATE = 'PACKAGE_CREATE',
  PACKAGE_MANAGE = 'PACKAGE_MANAGE',
  PACKAGE_CHANGE_STATUS = 'PACKAGE_CHANGE_STATUS',
}

export default Role;
